version: '3.1'

services:
    logio:
      build: ./
      image: ysukhy/alpine_logio:v1
      container_name: alpine-logio
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      ports:
      - "28778:28778"
      privileged: true
      environment:
      - PORT=28778
      - DOCKER_SOCKET=/var/run/docker.sock
      - SHOW_ALL_LOGS=true
      - LOGIO_HARVESTER_NODENAME=DockerLogs
      restart: always
